import Logo from '../public/companyLogo.png';
export const cardData = [
    {
        id: 0,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 1,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 2,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 3,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 4,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 5,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 6,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 7,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },

];

export const siteOptions = [
    { name: "linkedIn", label: "LinkedIn" },
    { name: "wellfound", label: "Wellfound" },
    { name: "glints", label: "Glints" },
    { name: "glassdoor", label: "Glassdoor" },
    { name: "indeed", label: "Indeed" },
    { name: "itviec", label: "ITviec" },
    { name: "vietnamworks", label: "Vietnamworks" },
    { name: "careerlinks", label: "Careerlinks" },
    { name: "topdev", label: "TopDev" },
];

export const languageOptions = [
    { value: "english", label: "English" },
    { value: "mandarin_chinese", label: "Mandarin Chinese" },
    { value: "hindi", label: "Hindi" },
    { value: "spanish", label: "Spanish" },
    { value: "french", label: "French" },
    { value: "standard_arabic", label: "Standard Arabic" },
    { value: "bengali", label: "Bengali" },
    { value: "portuguese", label: "Portuguese" },
    { value: "russian", label: "Russian" },
    { value: "urdu", label: "Urdu" },
    { value: "indonesian", label: "Indonesian" },
    { value: "german", label: "German" },
    { value: "japanese", label: "Japanese" },
    { value: "punjabi", label: "Punjabi" },
    { value: "marathi", label: "Marathi" },
    { value: "telugu", label: "Telugu" },
    { value: "tamil", label: "Tamil" },
    { value: "korean", label: "Korean" },
    { value: "wu chinese", label: "Wu Chinese" },
];

export const dataResistOptions = [
    { value: "5days", label: "5 days" },
    { value: "15days", label: "15 days" },
    { value: "30days", label: "30 days" },
    { value: "60days", label: "60 days" },
    { value: "90days", label: "90 days" },
];



export const skills = [
    { "value": 'nextjs', "label": 'Nextjs' },
    { "value": 'typescript', "label": 'Typescript' },
    { "value": 'tailwindcss', "label": 'Tailwindcss' },
    { "value": 'postcss', "label": 'Postcss' },
    { "value": 'supabase', "label": 'Supabase' },
    { "value": 'vercel', "label": 'Vercel' },
    { "value": 'docker', "label": 'Docker' },
    { "value": 'kubernetes', "label": 'Kubernetes' },
]

export const countryData = [
    { "name": "Albania", "code": "Albania" },
    { "name": "Åland Islands", "code": "Åland Islands" },
    { "name": "Algeria", "code": "Algeria" },
    { "name": "American Samoa", "code": "American Samoa" },
    { "name": "Andorra", "code": "Andorra" },
    { "name": "Angola", "code": "Angola" },
    { "name": "Anguilla", "code": "Anguilla" },
    { "name": "Antarctica", "code": "Antarctica" },
    { "name": "Antigua and Barbuda", "code": "Antigua and Barbuda" },
    { "name": "Argentina", "code": "Argentina" },
    { "name": "Armenia", "code": "Armenia" },
    { "name": "Aruba", "code": "Aruba" },
    { "name": "Australia", "code": "Australia" },
    { "name": "Austria", "code": "Austria" },
    { "name": "Azerbaijan", "code": "Azerbaijan" },
    { "name": "Bahamas (the)", "code": "Bahamas (the)" },
    { "name": "Bahrain", "code": "Bahrain" },
    { "name": "Bangladesh", "code": "Bangladesh" },
    { "name": "Barbados", "code": "Barbados" },
    { "name": "Belarus", "code": "Belarus" },
    { "name": "Belgium", "code": "Belgium" },
    { "name": "Belize", "code": "Belize" },
    { "name": "Benin", "code": "Benin" },
    { "name": "Bermuda", "code": "Bermuda" },
    { "name": "Bhutan", "code": "Bhutan" },
    { "name": "Bolivia (Plurinational State of)", "code": "Bolivia (Plurinational State of)" },
    { "name": "Bonaire, Sint Eustatius and Saba", "code": "Bonaire, Sint Eustatius and Saba" },
    { "name": "Bosnia and Herzegovina", "code": "Bosnia and Herzegovina" },
    { "name": "Botswana", "code": "Botswana" },
    { "name": "Bouvet Island", "code": "Bouvet Island" },
    { "name": "Brazil", "code": "Brazil" },
    { "name": "British Indian Ocean Territory (the)", "code": "British Indian Ocean Territory (the)" },
    { "name": "Brunei Darussalam", "code": "Brunei Darussalam" },
    { "name": "Bulgaria", "code": "Bulgaria" },
    { "name": "Burkina Faso", "code": "Burkina Faso" },
    { "name": "Burundi", "code": "Burundi" },
    { "name": "Cabo Verde", "code": "Cabo Verde" },
    { "name": "Cambodia", "code": "Cambodia" },
    { "name": "Cameroon", "code": "Cameroon" },
    { "name": "Canada", "code": "Canada" },
    { "name": "Cayman Islands (the)", "code": "Cayman Islands (the)" },
    { "name": "Central African Republic (the)", "code": "Central African Republic (the)" },
    { "name": "Chad", "code": "Chad" },
    { "name": "Chile", "code": "Chile" },
    { "name": "China", "code": "China" },
    { "name": "Christmas Island", "code": "Christmas Island" },
    { "name": "Cocos (Keeling) Islands (the)", "code": "Cocos (Keeling) Islands (the)" },
    { "name": "Colombia", "code": "Colombia" },
    { "name": "Comoros (the)", "code": "Comoros (the)" },
    { "name": "Congo (the Democratic Republic of the)", "code": "Congo (the Democratic Republic of the)" },
    { "name": "Congo (the)", "code": "Congo (the)" },
    { "name": "Cook Islands (the)", "code": "Cook Islands (the)" },
    { "name": "Costa Rica", "code": "Costa Rica" },
    { "name": "Croatia", "code": "Croatia" },
    { "name": "Cuba", "code": "Cuba" },
    { "name": "Curaçao", "code": "Curaçao" },
    { "name": "Cyprus", "code": "Cyprus" },
    { "name": "Czechia", "code": "Czechia" },
    { "name": "Côte d'Ivoire", "code": "Côte d'Ivoire" },
    { "name": "Denmark", "code": "Denmark" },
    { "name": "Djibouti", "code": "Djibouti" },
    { "name": "Dominica", "code": "Dominica" },
    { "name": "Dominican Republic (the)", "code": "Dominican Republic (the)" },
    { "name": "Ecuador", "code": "Ecuador" },
    { "name": "Egypt", "code": "Egypt" },
    { "name": "El Salvador", "code": "El Salvador" },
    { "name": "Equatorial Guinea", "code": "Equatorial Guinea" },
    { "name": "Eritrea", "code": "Eritrea" },
    { "name": "Estonia", "code": "Estonia" },
    { "name": "Eswatini", "code": "Eswatini" },
    { "name": "Ethiopia", "code": "Ethiopia" },
    { "name": "Falkland Islands (the) [Malvinas]", "code": "Falkland Islands (the) [Malvinas]" },
    { "name": "Faroe Islands (the)", "code": "Faroe Islands (the)" },
    { "name": "Fiji", "code": "Fiji" },
    { "name": "Finland", "code": "Finland" },
    { "name": "France", "code": "France" },
    { "name": "French Guiana", "code": "French Guiana" },
    { "name": "French Polynesia", "code": "French Polynesia" },
    { "name": "French Southern Territories (the)", "code": "French Southern Territories (the)" },
    { "name": "Gabon", "code": "Gabon" },
    { "name": "Gambia (the)", "code": "Gambia" },
    { "name": "Georgia", "code": "Georgia" },
    { "name": "Guadeloupe", "code": "Guadeloupe" },
    { "name": "Guam", "code": "Guam" },
    { "name": "Guatemala", "code": "Guatemala" },
    { "name": "Guernsey", "code": "Guernsey" },
    { "name": "Guinea", "code": "Guinea" },
    { "name": "Guinea-Bissau", "code": "Guinea-Bissau" },
    { "name": "Guyana", "code": "Guyana" },
    { "name": "Haiti", "code": "Haiti" },
    { "name": "Heard Island and McDonald Islands", "code": "Heard Island and McDonald Islands" },
    { "name": "Holy See (the)", "code": "Holy See (the)" },
    { "name": "Ireland", "code": "Ireland" },
    { "name": "Isle of Man", "code": "Isle of Man" },
    { "name": "Jersey", "code": "Jersey" },
    { "name": "Kazakhstan", "code": "Kazakhstan" },
    { "name": "Kiribati", "code": "Kiribati" },
    { "name": "Lao People's Democratic Republic (the)", "code": "Lao People's Democratic Republic (the)" },
    { "name": "Lesotho", "code": "Lesotho" },
    { "name": "Liechtenstein", "code": "Liechtenstein" },
    { "name": "Marshall Islands (the)", "code": "Marshall Islands (the)" },
    { "name": "Martinique", "code": "Martinique" },
    { "name": "Micronesia (Federated States of)", "code": "Micronesia (Federated States of)" },
    { "name": "Montserrat", "code": "Montserrat" },
    { "name": "Nauru", "code": "Nauru" },
    { "name": "Niue", "code": "Niue" },
    { "name": "Norfolk Island", "code": "Norfolk Island" },
    { "name": "Northern Mariana Islands (the)", "code": "Northern Mariana Islands (the)" },
    { "name": "Palau", "code": "Palau" },
    { "name": "Pitcairn", "code": "Pitcairn" },
    { "name": "Samoa", "code": "Samoa" },
    { "name": "Solomon Islands (the)", "code": "Solomon Islands (the)" },
    { "name": "Tokelau", "code": "Tokelau" },
    { "name": "Tuvalu", "code": "Tuvalu" },
    { "name": "Palestine, State of", "code": "Palestine, State of" },
    { "name": "Panama", "code": "Panama" },
    { "name": "Papua New Guinea", "code": "Papua New Guinea" },
    { "name": "Paraguay", "code": "Paraguay" },
    { "name": "Peru", "code": "Peru" },
    { "name": "Philippines (the)", "code": "Philippines (the)" },
    { "name": "Pitcairn", "code": "Pitcairn" },
    { "name": "Poland", "code": "Poland" },
    { "name": "Portugal", "code": "Portugal" },
    { "name": "Puerto Rico", "code": "Puerto Rico" },
    { "name": "Qatar", "code": "Qatar" },
    { "name": "Republic of North Macedonia", "code": "Republic of North Macedonia" },
    { "name": "Romania", "code": "Romania" },
    { "name": "Russian Federation (the)", "code": "Russian Federation (the)" },
    { "name": "Rwanda", "code": "Rwanda" },
    { "name": "Réunion", "code": "Réunion" },
    { "name": "Saint Barthélemy", "code": "Saint Barthélemy" },
    { "name": "Saint Helena, Ascension and Tristan da Cunha", "code": "Saint Helena, Ascension and Tristan da Cunha" },
    { "name": "Saint Kitts and Nevis", "code": "Saint Kitts and Nevis" },
    { "name": "Saint Lucia", "code": "Saint Lucia" },
    { "name": "Saint Martin (French part)", "code": "Saint Martin (French part)" },
    { "name": "Saint Pierre and Miquelon", "code": "Saint Pierre and Miquelon" },
    { "name": "Saint Vincent and the Grenadines", "code": "Saint Vincent and the Grenadines" },
    { "name": "Samoa", "code": "Samoa" },
    { "name": "San Marino", "code": "San Marino" },
    { "name": "Sao Tome and Principe", "code": "Sao Tome and Principe" },
    { "name": "Saudi Arabia", "code": "Saudi Arabia" },
    { "name": "Senegal", "code": "Senegal" },
    { "name": "Serbia", "code": "Serbia" },
    { "name": "Seychelles", "code": "Seychelles" },
    { "name": "Sierra Leone", "code": "Sierra Leone" },
    { "name": "Singapore", "code": "Singapore" },
    { "name": "Sint Maarten (Dutch part)", "code": "Sint Maarten (Dutch part)" },
    { "name": "Slovakia", "code": "Slovakia" },
    { "name": "Slovenia", "code": "Slovenia" },
    { "name": "Solomon Islands", "code": "Solomon Islands" },
    { "name": "Somalia", "code": "Somalia" },
    { "name": "South Africa", "code": "South Africa" },
    { "name": "South Georgia and the South Sandwich Islands", "code": "South Georgia and the South Sandwich Islands" },
    { "name": "South Sudan", "code": "South Sudan" },
    { "name": "Spain", "code": "Spain" },
    { "name": "Sri Lanka", "code": "Sri Lanka" },
    { "name": "Sudan (the)", "code": "Sudan (the)" },
    { "name": "Suriname", "code": "Suriname" },
    { "name": "Svalbard and Jan Mayen", "code": "Svalbard and Jan Mayen" },
    { "name": "Sweden", "code": "Sweden" },
    { "name": "Switzerland", "code": "Switzerland" },
    { "name": "Syrian Arab Republic", "code": "Syrian Arab Republic" },
    { "name": "Taiwan (Province of China)", "code": "Taiwan (Province of China)" },
    { "name": "Tajikistan", "code": "Tajikistan" },
    { "name": "Tanzania, United Republic of", "code": "Tanzania, United Republic of" },
    { "name": "Thailand", "code": "Thailand" },
    { "name": "Timor-Leste", "code": "Timor-Leste" },
    { "name": "Togo", "code": "Togo" },
    { "name": "Tonga", "code": "Tonga" },
    { "name": "Trinidad and Tobago", "code": "Trinidad and Tobago" },
    { "name": "Tunisia", "code": "Tunisia" },
    { "name": "Turkey", "code": "Turkey" },
    { "name": "Turkmenistan", "code": "Turkmenistan" },
    { "name": "Turks and Caicos Islands (the)", "code": "Turks and Caicos Islands (the)" },
    { "name": "Uganda", "code": "Uganda" },
    { "name": "Ukraine", "code": "Ukraine" },
    { "name": "United Arab Emirates (the)", "code": "United Arab Emirates (the)" },
    { "name": "United Kingdom of Great Britain and Northern Ireland (the)", "code": "United Kingdom of Great Britain and Northern Ireland (the)" },
    { "name": "United States Minor Outlying Islands (the)", "code": "United States Minor Outlying Islands (the)" },
    { "name": "United States of America (the)", "code": "United States of America (the)" },
    { "name": "Uruguay", "code": "Uruguay" },
    { "name": "Uzbekistan", "code": "Uzbekistan" },
    { "name": "Vanuatu", "code": "Vanuatu" },
    { "name": "Venezuela (Bolivarian Republic of)", "code": "Venezuela (Bolivarian Republic of)" },
    { "name": "Viet Nam", "code": "Viet Nam" },
    { "name": "Virgin Islands (British)", "code": "Virgin Islands (British)" },
    { "name": "Virgin Islands (U.S.)", "code": "Virgin Islands (U.S.)" },
    { "name": "Wallis and Futuna", "code": "Wallis and Futuna" },
    { "name": "Western Sahara", "code": "Western Sahara" },
    { "name": "Yemen", "code": "Yemen" },
    { "name": "Zambia", "code": "Zambia" },
    { "name": "Zimbabwe", "code": "Zimbabwe" }
]

