import Logo from '../public/logo.png';
export const cardData = [
    {
        id: 0,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 1,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 2,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 3,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 4,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 5,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 6,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },
    {
        id: 7,
        role: 'Junior Frontend Engineer',
        company: 'VNG Corporation',
        src: Logo,
        description: 'Fullstack Dev and Web3 Enthusiast',
        tags: ['2 years', 'Hydrid', '800 - 1200$'],
        skills: ['Nextjs, Typescript', 'Tailwindcss with postcss master', 'Supabase  experience over 2 years', 'Know how to use Vercel'],
        requirements: ['Bachelor in CS/SE or related field', '2 years of experience working with Fullstack role', 'Fast learner', 'Preferred: Docker/Kubernetes'],
    },

];